site_name: Scotty-Docs
pages:
- Home: 'index.md'
- Web Dev:
    - 'HTML': 'web-dev/html.md'
    - 'CSS': 'web-dev/css.md'
    - 'JavaScript': 'web-dev/javascript.md'
- Bash:
    - 'Bash': 'bash/bash.md'
    - 'Vim': 'bash/vim.md'
- ETC:
    - 'MkDocs': 'etc/mkdocs.md'
    - 'Markdown Syntax': 'etc/markdown-syntax.md'
# theme: readthedocs
